#!/usr/bin/env bash
# this bash script will install nginx on a webserver
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx restart
