#!/usr/bin/env bash
# install and configure the load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend http_frontend
    bind *:80
    mode http
    default_backend web_servers
backend web_servers
    balance roundrobin
    server 485479-web-01 54.152.135.240:80 check
    server 485479-web-02 54.145.84.203:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
