#!/usr/bin/env bash
# this script makes a symbolic link in the sites-enabled directory
rm /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available /etc/nginx/sites-enabled
service nginx restart
