#!/usr/bin/env bash
#this script will print hours and minutes till 12:59
min=1
h=0
echo Hour: $h
while [ $h != 13 ]
do
	if [ $min == 60 ]
	then
		if [ $h == 12 ]
			then
				break
		fi
		((h++))
		echo Hour: $h
		min=1
	fi
	echo $min
	((min++))
done
