#!/usr/bin/env bash
# Loop through each non-hidden file in the current directory
for file in *; do
    if [[ ! "$file" == .* && "$file" == *-* ]]; then
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
