#!/usr/bin/env bash
#install ufw and enable certain ports

sudo apt update
sudo apt install ufw


sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
